language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - TARGET=test

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: TARGET=cs_dry_run
    - php: 5.5
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: DEPENDENCIES="symfony/lts:^2"
    - php: 7.1
      env: DEPENDENCIES="symfony/lts:^3"
    - php: 7.1
      env: STABILITY="dev"
  allow_failures:
    - env: STABILITY="dev"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [[ -v $STABILITY ]]; then composer config minimum-stability $STABILITY; fi;
  - if [[ -v $DEPENDENCIES ]]; then composer require --no-update $DEPENDENCIES; fi;
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
 - make $TARGET
